# From Sprint 1

In [1]:
import numpy as np
import tensorflow #open source used for both ML and DL for computation
from tensorflow.keras.datasets import mnist #mnist dataset
from tensorflow.keras.models import Sequential #it is a plain stack of layers
from tensorflow.keras import layers #A Layer consists of a tensor- in tensor-out computat ion funct ion
from tensorflow.keras.layers import Dense, Flatten #Dense-Dense Layer is the regular deeply connected r
#faltten -used fot flattening the input or change the dimension
from tensorflow.keras.layers import Conv2D #onvoLutiona l Layer
from keras.optimizers import Adam #opt imizer
from keras. utils import np_utils #used for one-hot encoding
import matplotlib.pyplot as plt   #used for data visualization

In [2]:
(x_train, y_train), (x_test, y_test)=mnist.load_data() #splitting the mnist data

#Reshaping to format which CNN expects (batch, height, width, channels)
x_train=x_train.reshape (60000, 28, 28, 1).astype('float32')
x_test=x_test.reshape (10000, 28, 28, 1).astype ('float32')

#one hot encode
number_of_classes = 10  #storing the no of classes in a variable
y_train = np_utils.to_categorical (y_train, number_of_classes) #converts the output in binary format
y_test = np_utils.to_categorical (y_test, number_of_classes)

11490434/11490434 [==============================] - 0s 0us/step


# Add CNN Layers

In [3]:
#create model
model=Sequential ()

In [4]:
#adding model Layer
model.add(Conv2D(64, (3, 3), input_shape=(28, 28, 1), activation='relu'))
model.add(Conv2D(32, (3, 3), activation = 'relu'))
#model.add(conv2D(32, (3,3), activation = 'relu))

In [5]:
#flatten the dimension of the image
model.add(Flatten())

In [6]:
#output layer with 10 neurons
model.add(Dense(number_of_classes,activation = 'softmax'))

# Compiling the model

In [7]:
#Compile model
model.compile(loss= 'categorical_crossentropy', optimizer="Adam", metrics=['accuracy'])

# Train the model

In [8]:
#fit the model
model.fit(x_train, y_train, validation_data=(x_test, y_test), epochs=5, batch_size=32)

Epoch 1/5
1875/1875 [==============================] - 116s 61ms/step - loss: 0.2121 - accuracy: 0.9528 - val_loss: 0.0943 - val_accuracy: 0.9716
Epoch 2/5
1875/1875 [==============================] - 114s 61ms/step - loss: 0.0666 - accuracy: 0.9794 - val_loss: 0.0811 - val_accuracy: 0.9749
Epoch 3/5
1875/1875 [==============================] - 112s 60ms/step - loss: 0.0469 - accuracy: 0.9855 - val_loss: 0.1147 - val_accuracy: 0.9739
Epoch 4/5
1875/1875 [==============================] - 117s 63ms/step - loss: 0.0375 - accuracy: 0.9884 - val_loss: 0.1018 - val_accuracy: 0.9737
Epoch 5/5
1875/1875 [==============================] - 116s 62ms/step - loss: 0.0288 - accuracy: 0.9909 - val_loss: 0.0894 - val_accuracy: 0.9801


# Observing the metrics

In [9]:
# Final evaluation of the model
metrics = model.evaluate(x_test, y_test, verbose=0)
print("Metrics (Test loss &Test Accuracy): ")
print(metrics)

Metrics (Test loss &Test Accuracy): 
[0.08937656134366989, 0.9800999760627747]


# Test the Model

In [10]:
# Predicting the Output
prediction=model.predict(x_test[:4])
print(prediction)

1/1 [==============================] - 0s 103ms/step
[[1.0722897e-06 1.7141589e-18 2.7211833e-08 5.5105747e-09 3.1974950e-15
  6.2946589e-15 6.5320302e-18 9.9999893e-01 3.4854652e-10 5.1784710e-10]
 [1.4988335e-06 8.4020257e-09 9.9999845e-01 3.7803782e-09 5.5052344e-13
  5.7065228e-15 2.7968026e-08 3.3485599e-12 5.9428248e-12 4.5884652e-17]
 [7.9097688e-09 9.9999547e-01 2.7923343e-07 1.3466297e-11 2.1773940e-06
  1.5493918e-06 5.1607840e-10 7.0766210e-10 4.7427324e-07 2.2660923e-12]
 [9.9999952e-01 4.3404331e-17 1.5040059e-11 2.0475930e-11 8.6928763e-11
  7.8601734e-12 5.7869780e-09 8.7071747e-12 4.4690369e-11 4.2499522e-07]]


In [11]:
import numpy as np
print(np.argmax(prediction, axis=1)) #printing our Labels from first 4 images
print(y_test[:4]) #printing the actual Labels

[7 2 1 0]
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


# Save The model

In [12]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [14]:
%cd /content/drive/MyDrive/Projects

/content/drive/MyDrive/Projects


In [15]:
# Save the model
model.save('models/mnistCNN.h5')

# Test With Saved Model

In [31]:
# Taking images as input and checking results

# Importing the keras libraries and packages
from tensorflow.keras.models import load_model
model = load_model(r'/content/drive/MyDrive/Projects/models/mnistCNN.h5')
from PIL import Image #used for manipulating image upload by the user.
for index in range(4):
    img = Image.open("data/" + str(index) + ".png").convert('L') # convert image to monochrome
    img = img.resize((28,28)) # resizing of input image
    im2arr = np.array(img) #convert to image
    im2arr = im2arr.reshape(1,28,28,1) #reshaping according to our requirement
    #predicting the Test set results
    y_pred = model.predict(im2arr)
    print(y_pred)

1/1 [==============================] - 0s 51ms/step
[[5.6049165e-09 1.4067458e-05 9.9628639e-01 3.5655799e-03 6.2293903e-10
  5.4247762e-06 6.0663690e-05 1.1750326e-07 6.7713328e-05 5.4526826e-13]]
1/1 [==============================] - 0s 15ms/step
[[2.6514371e-08 9.9987853e-01 2.6678819e-09 5.0345729e-17 1.1578899e-04
  3.5318081e-13 1.3091828e-13 5.5813430e-06 1.7989708e-10 2.9838541e-09]]
1/1 [==============================] - 0s 17ms/step
[[3.7167319e-03 1.4217998e-03 8.2274787e-03 7.9998100e-01 1.1364324e-01
  2.0436779e-02 6.3992090e-08 3.5715982e-02 3.3161716e-05 1.6823808e-02]]
1/1 [==============================] - 0s 16ms/step
[[3.89392152e-02 1.03533266e-05 1.84860080e-01 2.39315932e-03
  2.41028378e-04 8.98893850e-05 1.02114845e-02 3.54044059e-05
  7.63198674e-01 2.07284338e-05]]
